// frontend/src/components/modals/AssignCampaignsModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { Campaign, AssignCampaignsRequest } from '@/types'

const props = defineProps<{
  show: boolean
  accountId: string
  accountEmail: string
  currentCampaigns: string[]
  availableCampaigns: Campaign[]
}>()

const emit = defineEmits<{
  close: []
  assign: [data: AssignCampaignsRequest]
}>()

const selectedIds = ref<string[]>([])

watch(
  () => props.show,
  (open) => {
    if (open) {
      selectedIds.value = [...(props.currentCampaigns || [])]
    }
  }
)

function toggleCampaign(id: string) {
  const idx = selectedIds.value.indexOf(id)
  if (idx === -1) {
    selectedIds.value.push(id)
  } else {
    selectedIds.value.splice(idx, 1)
  }
}

function handleSubmit() {
  emit('assign', { campaign_ids: selectedIds.value })
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center">
      <div class="absolute inset-0 bg-black/50" @click="emit('close')" />
      <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 max-h-[90vh] overflow-y-auto">
        <!-- Header -->
        <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">Assign Campaigns</h2>
          <button class="text-gray-400 hover:text-gray-600 p-1" @click="emit('close')">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="p-6 space-y-4">
          <p class="text-sm text-gray-600">
            Select campaigns for <strong>{{ accountEmail }}</strong>
          </p>

          <div v-if="availableCampaigns.length === 0" class="p-4 text-center text-gray-500 text-sm">
            No campaigns available. Create a campaign first.
          </div>

          <div v-else class="space-y-2 max-h-60 overflow-y-auto">
            <label
              v-for="campaign in availableCampaigns"
              :key="campaign.id"
              class="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 cursor-pointer transition-colors"
              :class="selectedIds.includes(campaign.id) ? 'border-blue-300 bg-blue-50' : ''"
            >
              <input
                type="checkbox"
                :checked="selectedIds.includes(campaign.id)"
                class="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500"
                @change="toggleCampaign(campaign.id)"
              />
              <div>
                <div class="text-sm font-medium text-gray-900">{{ campaign.name }}</div>
                <div class="text-xs text-gray-500">{{ campaign.status }}</div>
              </div>
            </label>
          </div>
        </div>

        <!-- Footer -->
        <div class="px-6 py-4 border-t border-gray-100 flex justify-end gap-3">
          <button class="px-4 py-2 text-sm text-gray-600 hover:text-gray-800" @click="emit('close')">
            Cancel
          </button>
          <button
            class="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
            @click="handleSubmit"
          >
            Save ({{ selectedIds.length }} selected)
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// components/AssignCampaignsModal.tsx
'use client'

import { useState } from 'react'

interface AssignCampaignsModalProps {
  isOpen: boolean
  onClose: () => void
  accountId: string
  accountEmail: string
  currentCampaigns: string[]
  availableCampaigns: Array<{ id: string; name: string; status: string }>
  onAssign: (accountId: string, campaignIds: string[]) => Promise<void>
}

export default function AssignCampaignsModal({
  isOpen,
  onClose,
  accountId,
  accountEmail,
  currentCampaigns,
  availableCampaigns,
  onAssign
}: AssignCampaignsModalProps) {
  const [selectedCampaigns, setSelectedCampaigns] = useState<string[]>(currentCampaigns)
  const [loading, setLoading] = useState(false)

  if (!isOpen) return null

  const handleToggleCampaign = (campaignId: string) => {
    if (selectedCampaigns.includes(campaignId)) {
      setSelectedCampaigns(selectedCampaigns.filter(id => id !== campaignId))
    } else {
      setSelectedCampaigns([...selectedCampaigns, campaignId])
    }
  }

  const handleSubmit = async () => {
    setLoading(true)
    try {
      await onAssign(accountId, selectedCampaigns)
      onClose()
    } catch (error) {
      console.error('Failed to assign campaigns:', error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-md w-full">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
          <h2 className="text-xl font-semibold text-gray-900">Assign Campaigns</h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="mb-4">
            <p className="text-sm text-gray-600">
              Assign campaigns to <span className="font-medium text-gray-900">{accountEmail}</span>
            </p>
          </div>

          {availableCampaigns.length === 0 ? (
            <div className="text-center py-8">
              <p className="text-gray-500">No campaigns available</p>
              <p className="text-sm text-gray-400 mt-1">Create a campaign first to assign it</p>
            </div>
          ) : (
            <div className="space-y-2 max-h-96 overflow-y-auto">
              {availableCampaigns.map((campaign) => (
                <label
                  key={campaign.id}
                  className="flex items-center space-x-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 cursor-pointer transition-colors"
                >
                  <input
                    type="checkbox"
                    checked={selectedCampaigns.includes(campaign.id)}
                    onChange={() => handleToggleCampaign(campaign.id)}
                    className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                  />
                  <div className="flex-1">
                    <p className="text-sm font-medium text-gray-900">{campaign.name}</p>
                    <p className="text-xs text-gray-500">
                      Status: <span className="capitalize">{campaign.status}</span>
                    </p>
                  </div>
                </label>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 flex items-center justify-between">
          <p className="text-sm text-gray-600">
            {selectedCampaigns.length} campaign{selectedCampaigns.length !== 1 ? 's' : ''} selected
          </p>
          <div className="flex space-x-3">
            <button
              onClick={onClose}
              disabled={loading}
              className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 font-medium transition-colors disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              onClick={handleSubmit}
              disabled={loading}
              className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 flex items-center space-x-2"
            >
              {loading && (
                <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
              )}
              <span>Assign</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
